name: Build
on:
  push:
    branches-ignore:
    - release*
  pull_request:
    branches-ignore:
    - release
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build SDK
      run: dotnet build -c Release --no-restore
